name: Factionitems
description: Items supplémentaire pour le mode faction d'Oerthyon
author: Superkooka <aymeric.gueracague@gmail.com>
version: 1.0.0
main: com.superkooka.oerthyon.factionitems.Main
api-version: 1.8
website: github.com/Oerthyon/FactionItems

depend:
  - HolographicDisplays

softdepend:
  - Factions

commands:
  rtp:
    description: Permet de se téléporter aléatoirement sur la carte
    usage: /rtp
  factionitems:
    description: Permet de recuperer les items spécifique au faction
    usage: /factionitems give <pseudo> <item> [amount] [...options]

default-permission: op

permissions:
  oerthyon.factionitems.*:
    description: Toutes les permissions du plugin
    default: op
    children:
      oerthyon.factionitems.chunkbuster.*: true
      oethyon.factionitems.dynamite.*: true
      oerthyon.factionitems.sword.*: true
      oerthyon.factionitems.pickaxe.*: true


  oerthyon.factionitems.chunkbuster.*:
    description: Toutes les permissions du chunkbuster
    default: op
    children:
      oerthyon.factionitems.chunkbuster.give: true
      oerthyon.factionitems.chunkbuster.use: true
      oerthyon.factionitems.chunkbuster.bust_command: true
      oerthyon.factionitems.chunkbuster.use_everywhere: true

  oerthyon.factionitems.chunkbuster.give:
    description: donne la permission de donner le chunkbuster.
    default: op

  oerthyon.factionitems.chunkbuster.use:
    description: donne la permission d'utiliser cette chunkbuster.
    default: true

  oerthyon.factionitems.chunkbuster.bust_command:
    description: donne la permission d'utiliser /chunkbuster bust <x> <z>.
    default: op

  oerthyon.factionitems.chunkbuster.use_everywhere:
    description: donne la permission d'utiliser un chunkbuster partout, même hors de sa faction.
    default: op

  oethyon.factionitems.dynamite.*:
    description: donne toute les permisssions lié au dynamite
    default: op
    children:
      oerthyon.factionitems.dynamite.give: true
      oerthyon.factionitems.dynamite.use: true


  oethyon.factionitems.dynamite.give:
    description: donne la permission give une dynamite
    default: op

  oethyon.factionitems.dynamite.use:
    description: donne la permission d'utiliser une dynamite
    default: true

  oerthyon.factionitems.sword.*:
    description: donne toutes les permissions liée aux épées
    default: op
    children:
      oerthyon.factionitems.sword.epic.*: true

  oerthyon.factionitems.sword.epic.*:
    description: donne toutes les permissions liée aux épées epic
    default: op
    children:
      oerthyon.factionitems.sword.epic.give: true
      oerthyon.factionitems.sword.epic.use: true

  oerthyon.factionitems.sword.epic.give:
    description: donne la permission de se give une épée epic
    default: false

  oerthyon.factionitems.sword.epic.use:
    description: donne la permission d'utiliser une épée epic
    default: true


  oerthyon.factionitems.pickaxe.*:
    description: donne toutes les permissions lié aux pioches
    default: op
    children:
      oerthyon.factionitems.pickaxe.epic.*: true
      oerthyon.factionitems.pickaxe.legendary.*: true

  oerthyon.factionitems.pickaxe.epic.*:
    description: donne toutes les permissions lié aux pioches epic
    default: op
    children:
      oerthyon.factionitems.pickaxe.epic.give: true
      oerthyon.factionitems.pickaxe.epic.use: true

  oerthyon.factionitems.pickaxe.epic.give:
    description: donne la permission de se give une pioche epic
    default: false

  oerthyon.factionitems.pickaxe.epic.use:
    description: donne la permission d'utiliser une pioche epic
    default: true

  oerthyon.factionitems.pickaxe.legendary.*:
    description: donne toutes les permissions lié aux pioches legendaire
    default: op
    children:
      oerthyon.factionitems.pickaxe.legendary.give: true
      oerthyon.factionitems.pickaxe.legendary.use: true

  oerthyon.factionitems.pickaxe.legendary.give:
    description: donne la permission de se give une pioche legendary
    default: false

  oerthyon.factionitems.pickaxe.legendary.use:
    description: donne la permission d'utiliser une pioche legendary
    default: true
